# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the project
COPY . .

# Run prepare script to chmod the executables if needed
RUN npm run prepare

# Expose any port if needed (not explicitly required as MCP uses stdio usually)

# Start the MCP server
ENTRYPOINT ["node", "mcp-server/server.js"]
