name: Version & Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  version:
    name: Version & Publish Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install root dependencies
        run: npm ci

      - name: Install extension dependencies
        working-directory: apps/extension
        run: npm ci

      - name: Install vsce and ovsx globally
        run: npm install -g @vscode/vsce ovsx

      - name: Make release script executable
        run: chmod +x scripts/release.sh

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          publish: ./scripts/release.sh
          title: "Release: Extension Version Packages"
          commit: "chore: release extension packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }} 